#!/bin/bash

echo "🔍 Webhook Debugging Guide"
echo "=========================="
echo ""
echo "1️⃣  Stellen Sie sicher, dass ngrok läuft:"
echo "   ngrok http 3000"
echo ""
echo "2️⃣  Überprüfen Sie die ngrok URL (z.B. https://5383b898b7ba.ngrok-free.app)"
echo ""
echo "3️⃣  Im Clerk Dashboard konfigurieren:"
echo "   - Dashboard → Webhooks → + Add Endpoint"
echo "   - URL: https://your-ngrok-url.ngrok.io/api/webhooks/clerk"
echo "   - Events: user.created, user.updated, user.deleted"
echo "   - Signing Secret kopieren"
echo ""
echo "4️⃣  .env.local aktualisieren:"
echo "   WEBHOOK_SECRET=whsec_xxxxx"
echo ""
echo "5️⃣  Terminal-Logs überprüfen (npm run dev sollte laufen)"
echo "   Suchen Sie nach:"
echo "   - '🔔 Webhook received from Clerk'"
echo "   - '✅ User created/updated in MongoDB'"
echo "   - '❌ Fehler' (wenn es Probleme gibt)"
echo ""
echo "6️⃣  Test durchführen:"
echo "   - Erstellen Sie einen neuen Benutzer auf:"
echo "     https://5383b898b7ba.ngrok-free.app/sign-up"
echo "   - Überprüfen Sie die Terminal-Logs"
echo "   - Führen Sie aus: node check-users.mjs"
echo ""
echo "7️⃣  Im Clerk Dashboard testen:"
echo "   - Webhooks → Ihr Endpoint → Send Test Event"
echo "   - Wählen Sie 'user.created'"
echo "   - Klicken Sie 'Send Test'"
echo "   - Terminal sollte zeigen: '🔔 Webhook received from Clerk'"
echo ""
echo "Häufige Fehler:"
echo "- '❌ WEBHOOK_SECRET is not set' → .env.local prüfen"
echo "- '❌ Missing svix headers' → Webhook-Signatur falsch"
echo "- '❌ Signature verification failed' → Wrong Secret"
echo "- '❌ Duplicate email/username' → User existiert bereits"
echo ""
echo "MongoDB überprüfen:"
echo "   node check-users.mjs"
echo ""
