import type { Metadata } from 'next';
import '../globals.css';
import Header from '@/app/components/Header';
import ThemeProviderClient from '@/app/components/ThemeProviderClient';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeModeScript } from 'flowbite-react';
import Footer from '@/app/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <>
        <ClerkProvider>
          <ThemeProviderClient>
            <Header />
            {children}
            <Footer />
          </ThemeProviderClient>
        </ClerkProvider>
      </>
    </html>
  );
}
