import type { Metadata } from 'next';
import Script from 'next/script';
import ThemeProviderClient from '@/app/components/ThemeProviderClient';
import Header from '@/app/components/Header';
import Footer from '@/app/components/Footer';
import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';
import ThemeCom from '@/app/components/ThemeCom';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  
  return (
    <>
      <Script
        src="../components/ThemeCom.jsx"
        strategy="beforeInteractive"
      />
      
        <ThemeProviderClient>
          {/* If ThemeCom is a React client component, render it directly */}
          <ThemeCom children={undefined} />
          <Header />
          {children}
          <Footer />
        </ThemeProviderClient>
      
    </>
  );

}
